a = 1;
a = "111"

print(a);


def f(b){
    print(b)
    }

f(222);



def ff(a, b){
print(a, b)
return
}

ff(1, 1)

print(a)




def a(){
    b = 1111111
    def c(){
        def d(){
            print(b)
        }
        d()
    }
    c()
}
a()


def a(b){
    print(b)
}

a("aaaa")
def a(b){
    print(b)
    return
}

a("aaaa")
def a(b){
    print(b)
    return b
}

b = a("aaaa")
print(b)


def a(){
    return
}
print(a())
def a(){
    return 1
}
print(a())



def a(){
    def b(){
        print("b")
    }
    return b
}

b = a()
b()