def Man(){

    def this(){}

    def say(word){
        print(this.name, "say:", word)
    }

    this.name = "Man"
    this.age = 11
    this.say = say

    return this

}


def Child(){
    def this(){}
    this.super = Man()
    this.age = 1

    return this
}

a = Child()


a.super.say(111111)




def new_Obj(name){
    def this(){}

    def init(){
        this.name = name
        this.say = say
    }

    def say(){
        print("my name is ", this.name)
    }

    this.init = init
    return this
}


a = new_Obj("AAAA")
a.init()
a.say()






