a = 1

if a{
    b = 1
    if b{
        print(a, b)
    }
}


print("===============================================")

a = 1
print(a < 100)
for a < 100 {
    a = a + 1
    print(a)
}

print("===============================================")

if a == 1{

    print(1)
}elif a == 2{

    print(2)

}else{
    print("a", a)

    if a != 1 {

        print(a)
    }else{
        print(1)
    }

}

print("===============================================")

a = 1
b = 0
for a < 100 {
    print(a)
    a = a + 1

    for a < 100 {
        a = a + 1
        print("for 2, a=", a)
    }

    print("end", a)



    def b(){}
    b()

}



print("===============================================")



a = 10
for 1{
    a = a - 1
    if a <= 0 {
        break
    }
    if a > 5 {
        continue
    }
    print(a)

    b = 1
    for 1{
        b = b + 1
        if b > 100 {
            break
        }
        print(b, "b========")
    }

}
